# Replace the text below to customize your site
site_name: No Time Like The Past
site_description: Fight your way through a horde in this... 
site_author: Dub Derks en Morris Boverhuis
copyright: Copyright 2022 Dub Derks en Morris Boverhuis

site_url: https://localhost:8000/

extra_javascript:
  - js/p5.min.js
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

theme:
  name: material
  palette:
     # Palette toggle for light mode
    - scheme: default
       # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
      primary: light blue
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    
  font:
    # See available fonts at https://fonts.google.com/
    text: Open Sans
    code: Ubuntu Mono
  icon:
    logo: material/cake-variant-outline
  favicon: images/cake-variant-outline.svg
  features:
    - navigation.instant
    - content.code.annotate

plugins:
  - search
  - mermaid2
  - mkdocs-video
  - git-revision-date-localized:
      fallback_to_build_date: true
      # Read more: https://timvink.github.io/mkdocs-git-revision-date-localized-plugin/options/#enabled
      enabled: !ENV [ENABLED_GIT_REVISION_DATE, False]  


markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.keys
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details  
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
